Table migrations {
  id_migration uuid [primary key]
  mimic_version varchar
  created_at timestamp
  updated_at timestamp
  migration_name varchar /*nullable*/
  resolved boolean /* default_false */
}

Table users {
  id_user uuid [primary key]
  name varchar
}

Table user_system {
  id_user uuid [primary key]
  id_system uuid [primary key]
}
Ref: "user_system"."id_user" > "users"."id_user"
Ref: "user_system"."id_system" > "systems"."id_system"

Table user_role {
  id_user uuid [primary key]
  id_role uuid [primary key]
}
Ref: "user_role"."id_user" > "users"."id_user"
Ref: "user_role"."id_role" > "roles"."id_role"

Table roles {
  id_role uuid [primary key]
  name varchar 
  is_default bool
  roleless_add bool
}
Ref: "roles"."id_role" > "entities"."id_entity"

Table access {
  id_access uuid [primary key]
  id_entity_to_access uuid /*nullable*/
  id_game_state uuid /*nullable*/
  scope enum("self", "same", "other")
  can_read boolean
  can_use boolean
  can_update boolean
  can_create boolean
  can_delete boolean
  can_overwrite boolean
}
Ref: "access"."id_entity_to_access" > "entities"."id_entity"
Ref: "access"."id_game_state" > "game_states"."id_game_state"
Ref: "access"."id_access" > "entities"."id_entity"

Table role_access {
  id_access uuid [primary key]
  id_role uuid [primary key]
}
Ref: "role_access"."id_role" > "roles"."id_role"
Ref: "role_access"."id_access" > "access"."id_access"

Table sheet_types {
  id_sheet_type uuid [primary key]
  name varchar 
  id_validation_rule uuid
  id_compose_rule uuid
  id_base_generator uuid // (optional)
}
Ref: "sheet_types"."id_sheet_type" > "entities"."id_entity"
Ref: "sheet_types"."id_validation_rule" > "rules"."id_rule"
Ref: "sheet_types"."id_compose_rule" > "rules"."id_rule"
Ref: "sheet_types"."id_base_generator" > "generators"."id_generator"

Table sheets {
  id_sheet uuid [primary key]
  id_sheet_type uuid
}
Ref: "sheets"."id_sheet" > "entities"."id_entity"
Ref: "sheets"."id_sheet_type" > "sheet_types"."id_sheet_type"

Table sheet_groups {
  id_sheet_group uuid [primary key]
  name varchar
}
Ref: "sheet_groups"."id_sheet_group" > "entities"."id_entity"

Table sheet_group_sheet {
  id_sheet_group uuid [primary key]
  id_sheet uuid [primary key]
}
Ref: "sheet_group_sheet"."id_sheet_group" > "sheet_groups"."id_sheet_group"
Ref: "sheet_group_sheet"."id_sheet" > "sheets"."id_sheet"

Table generator_types {
  id_generator_type uuid [primary key]
  name varchar
  id_validation_rule uuid
  id_compose_rule uuid
}
Ref: "generator_types"."id_generator_type" > "entities"."id_entity"
Ref: "generator_types"."id_validation_rule" > "rules"."id_rule"
Ref: "generator_types"."id_compose_rule" > "rules"."id_rule"

Table generator_type_steps {
  id_generator_type_step uuid [primary key]
  id_generator_type uuid
  id_validation_rule uuid
  name varchar
}
Ref: "generator_type_steps"."id_generator_type_step" > "entities"."id_entity"
Ref: "generator_type_steps"."id_generator_type" > "generator_types"."id_generator_type"
Ref: "generator_type_steps"."id_validation_rule" > "rules"."id_rule"

Table generators {
  id_generator uuid [primary key]
  id_generator_type uuid
  id_super_generator uuid /* nullable */
  is_children boolean /*default false*/
  name varchar
}
Ref: "generators"."id_generator" > "entities"."id_entity"
Ref: "generators"."id_generator_type" > "generator_types"."id_generator_type"
Ref: "generators"."id_super_generator" > "generators"."id_generator"

Table generator_steps {
  id_generator_step uuid [primary key]
  id_generator uuid
  id_generator_type_step uuid
  id_validation_rule uuid /* nullable */
  name varchar
}
Ref: "generator_steps"."id_generator_step" > "entities"."id_entity"
Ref: "generator_steps"."id_generator" > "generators"."id_generator"
Ref: "generator_steps"."id_generator_type_step" > "generator_type_steps"."id_generator_type_step"
Ref: "generator_steps"."id_validation_rule" > "rules"."id_rule"

Table generator_step_skill {
  id_generator_step_skill uuid [primary key]
  id_generator_step uuid
  id_skill uuid
}
Ref: "generator_step_skill"."id_generator_step" > "generator_steps"."id_generator_step"
Ref: "generator_step_skill"."id_skill" > "skills"."id_skill"

Table generator_step_skill_attribute_entry {
  id_generator_step_skill_attribute uuid [primary key]
  id_generator_step_skill uuid
  id_attribute uuid
  attribute_number number /*nullable*/
  attribute_string varchar /*nullable*/
  attribute_boolean boolean /*nullable*/
  attribute_entity uuid /*nullable*/
  order integer
}
Ref: "generator_step_skill_attribute_entry"."id_generator_step_skill" > "generator_step_skill"."id_generator_step_skill"
Ref: "generator_step_skill_attribute_entry"."id_attribute" > "attributes"."id_attribute"
Ref: "generator_step_skill_attribute_entry"."attribute_entity" > "entities"."id_entity"

Table sheet_type_generator_type {
  id_sheet_type_generator_type uuid [primary key]
  id_sheet_type uuid
  id_generator_type uuid
  order integer
}
Ref: "sheet_type_generator_type"."id_sheet_type" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_generator_type"."id_generator_type" > "generator_types"."id_generator_type"

Table skill_types {
  id_skill_type uuid [primary key]
  name varchar 
  id_validation_rule uuid
}
Ref: "skill_types"."id_skill_type" > "entities"."id_entity"
Ref: "skill_types"."id_validation_rule" > "rules"."id_rule"

Table skills {
  id_skill uuid [primary key]
  id_skill_type uuid
  name varchar
  id_action_rule uuid
}
Ref: "skills"."id_skill" > "entities"."id_entity"
Ref: "skills"."id_skill_type" > "skill_types"."id_skill_type"
Ref: "skills"."id_action_rule" > "rules"."id_rule"

Table skill_type_generator_type {
  id_skill_type uuid [primary key]
  id_generator_type uuid [primary key]
}
Ref: "skill_type_generator_type"."id_skill_type" > "skill_types"."id_skill_type"
Ref: "skill_type_generator_type"."id_generator_type" > "generator_types"."id_generator_type"

Table rules {
  id_rule uuid [primary key]
  name varchar
  type enum("math", "validation", "action", "relationship", "trigger")
  id_trigger_rule uuid /*nullable*/
  rule jsonb /*ast*/
}
Ref: "rules"."id_rule" > "entities"."id_entity"
Ref: "rules"."id_trigger_rule" > "rules"."id_rule"

Table rule_entity {

  id_rule uuid [primary key]
  id_entity uuid [primary key]
  resolve_method enum("manual", "context")
  value_type uuid
  internal_name varchar

}
Ref: "rule_entity"."id_rule" > "rules"."id_rule"
Ref: "rule_entity"."id_entity" > "entities"."id_entity"
Ref: "rule_entity"."value_type" > "value_types"."id_value_type"

Table rngs {
  id_rng uuid [primary key]
  name varchar 
  id_filter_rule uuid /*nullable*/
  expected_value integer /*nullable*/
  generator_start integer /*default 1*/
  generator_end integer
  generator_step integer /*default 1*/
  final_values integer[]
}
Ref: "rngs"."id_rng" > "entities"."id_entity"
Ref: "rngs"."id_filter_rule" > "rules"."id_rule"

Table value_types {
  id_value_type uuid [primary key]
  value_type enum("number", "string", "boolean", "entity")
  struct_type enum("value", "list")
}

Table attributes {
  id_attribute uuid [primary key]
  id_value_rule uuid
  name varchar 
  value_type uuid
  expected_value_number number /*nullable*/
  expected_value_string varchar /*nullable*/
  expected_value_boolean boolean /*nullable*/
  expected_value_entity uuid /*nullable*/
  default_value_number number /*nullable*/
  default_value_string varchar /*nullable*/
  default_value_boolean boolean /*nullable*/
  default_value_entity uuid /*nullable*/
  is_composable boolean /*default true*/
  is_constant boolean /*default false*/
}
Ref: "attributes"."id_attribute" > "entities"."id_entity"
Ref: "attributes"."id_value_rule" > "rules"."id_rule"
Ref: "attributes"."value_type" > "value_types"."id_value_type"
Ref: "attributes"."expected_value_entity" > "entities"."id_entity"
Ref: "attributes"."default_value_entity" > "entities"."id_entity"

Table entity_attribute {
  id_entity_attribute uuid [primary key]
  id_entity uuid
  id_attribute uuid
}
Ref: "entity_attribute"."id_entity" > "entities"."id_entity"
Ref: "entity_attribute"."id_attribute" > "attributes"."id_attribute"

Table entity_attribute_entry {
  id_entity_attribute_entry uuid [primary key]
  attribute_number number /*nullable*/
  attribute_string varchar /*nullable*/
  attribute_boolean boolean /*nullable*/
  attribute_entity uuid /*nullable*/
  order integer
}
Ref: "entity_attribute_entry"."id_entity_attribute_entry" > "entity_attribute"."id_entity_attribute"
Ref: "entity_attribute_entry"."attribute_entity" > "entities"."id_entity"

Table attribute_items {
  id_attribute_item uuid [primary key]
  id_attribute_composer uuid
  id_attribute_composable uuid
  name varchar
}
Ref: "attribute_items"."id_attribute_composer" > "attributes"."id_attribute"
Ref: "attribute_items"."id_attribute_composable" > "attributes"."id_attribute"

Table globals {
  id_global uuid [primary key]
  id_attribute uuid
  name varchar
}
Ref: "globals"."id_global" > "entities"."id_entity"
Ref: "globals"."id_attribute" > "attributes"."id_attribute"

Table test_types {
  id_test_type uuid [primary key]
  id_rule uuid
  name varchar
}
Ref: "test_types"."id_test_type" > "entities"."id_entity"
Ref: "test_types"."id_rule" > "rules"."id_rule"

Table tests {
  id_test uuid [primary key]
  id_test_type uuid
  name varchar 
}
Ref: "tests"."id_test" > "entities"."id_entity"
Ref: "tests"."id_test_type" > "test_types"."id_test_type"

Table test_rng {
  id_test uuid [primary key]
  id_rng uuid [primary key]
}
Ref: "test_rng"."id_test" > "tests"."id_test"
Ref: "test_rng"."id_rng" > "rngs"."id_rng"

Table game_states {
  id_game_state uuid [primary key]
  name varchar 
  turn_count_rule_id uuid
  turn_order_rule_id uuid
}
Ref: "game_states"."id_game_state" > "entities"."id_entity"
Ref: "game_states"."turn_count_rule_id" > "rules"."id_rule"
Ref: "game_states"."turn_order_rule_id" > "rules"."id_rule"

Table systems {
  id_system uuid [primary key]
  mimic_version varchar
  name varchar
  system_version varchar
  id_author_user uuid
  system_hash varchar
  created_at timestamp
  updated_at timestamp
  type enum("root", "delta")
  id_delta_origin uuid /*nullable*/
  actual_game_state uuid
  actual_turn uuid
}
Ref: "systems"."id_delta_origin" > "systems"."id_system"
Ref: "systems"."id_author_user" > "users"."id_user"
Ref: "systems"."actual_game_state" > "game_states"."id_game_state"
Ref: "systems"."actual_turn" > "entities"."id_entity"

Table event_logs {

  id_event_log uuid [primary key]
  created_at timestamp
  id_entity uuid
  event_type enum("free", "mimic")
  mimic_event enum("read", "use", "update", "create", "delete", "overwrite") /*nullable*/
  entry text
  multi_part_id uuid /*nullable*/
  resolved boolean /*default true*/

}
Ref: "event_logs"."id_entity" > "entities"."id_entity"

Table tags {
  id_tag uuid [primary key]
  id_system uuid
  name varchar 
}
Ref: "tags"."id_system" > "systems"."id_system"

Table tag_entity {
  id_tag uuid [primary key]
  id_entity uuid [primary key]
}
Ref: "tag_entity"."id_tag" > "tags"."id_tag"
Ref: "tag_entity"."id_entity" > "entities"."id_entity"

Table entities {
  id_entity uuid [primary key]
  created_at timestamp
  updated_at timestamp
  id_system uuid
  id_creator_user uuid
  id_overrides_entity uuid /*nullable*/
  table_name varchar /*ex: generators, rules, roles etc*/
  is_active bool /*default true*/
}
Ref: "entities"."id_overrides_entity" > "entities"."id_entity"
Ref: "entities"."id_creator_user" > "users"."id_user"
Ref: "entities"."id_system" > "systems"."id_system"

Table maps {
  id_map uuid [primary key]
  name varchar 
  size_a integer
  size_b integer
  size_c integer
  map_system enum("xyz", "qrs", "zones")
}
Ref: "maps"."id_map" > "entities"."id_entity"

Table map_token {
  id_map_token uuid [primary key]
  id_sheet uuid /*nullable*/
  id_map uuid
  position_a integer
  position_b integer
  position_c integer
  size_a integer
  size_b integer
  size_c integer
  origin_a integer
  origin_b integer
  origin_c integer
  angle_a integer /*0-360*/
  angle_b integer /*0-360*/
  angle_c integer /*0-360*/
  solid_level integer
}
Ref: "map_token"."id_map_token" > "entities"."id_entity"
Ref: "map_token"."id_sheet" > "sheets"."id_sheet"
Ref: "map_token"."id_map" > "maps"."id_map"

Table description_variant_types {
  id_description_variant_type uuid [primary key]
  id_system uuid
  name varchar
}
Ref: "description_variant_types"."id_system" > "systems"."id_system"

Table description_variants {
  id_description_variant uuid [primary key]
  id_description_variant_type uuid
  name varchar
}
Ref: "description_variants"."id_description_variant_type" > 
"description_variant_types"."id_description_variant_type"

Table descriptions {
  id_description uuid [primary key]
  id_entity uuid
  name varchar
  description text
  id_description_variant uuid
}
Ref: "descriptions"."id_entity" > "entities"."id_entity"
Ref: "descriptions"."id_description_variant" > 
"description_variants"."id_description_variant"

Table sheet_generator {
  id_sheet_generator uuid [primary key]
  id_sheet uuid
  id_generator uuid
  order integer
}
Ref: "sheet_generator"."id_sheet" > "sheets"."id_sheet"
Ref: "sheet_generator"."id_generator" > "generators"."id_generator"

Table sheet_skill {
  id_sheet_skill uuid [primary key]
  id_sheet uuid
  id_skill uuid
}
Ref: "sheet_skill"."id_sheet" > "sheets"."id_sheet"
Ref: "sheet_skill"."id_skill" > "skills"."id_skill"

Table sheet_skill_attribute_entry {
  id_sheet_skill_attribute uuid [primary key]
  id_sheet_skill uuid
  id_attribute uuid
  attribute_number number /*nullable*/
  attribute_string varchar /*nullable*/
  attribute_boolean boolean /*nullable*/
  attribute_entity uuid /*nullable*/
  order integer
}
Ref: "sheet_skill_attribute_entry"."id_sheet_skill" > "sheet_skill"."id_sheet_skill"
Ref: "sheet_skill_attribute_entry"."id_attribute" > "attributes"."id_attribute"
Ref: "sheet_skill_attribute_entry"."attribute_entity" > "entities"."id_entity"

Table sheet_type_sheet_type {
  id_sheet_type_main uuid [primary key]
  id_sheet_type_children uuid [primary key]
  id_relationship_rule uuid
}
Ref: "sheet_type_sheet_type"."id_sheet_type_main" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_sheet_type"."id_sheet_type_children" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_sheet_type"."id_relationship_rule" > "rules"."id_rule"

Table sheet_sheet {
  id_sheet_sheet uuid [primary key]
  id_sheet_main uuid
  id_sheet_children uuid
  order integer
}
Ref: "sheet_sheet"."id_sheet_main" > "sheets"."id_sheet"
Ref: "sheet_sheet"."id_sheet_children" > "sheets"."id_sheet"
