Table mimic_migrations {
  id uuid [primary key]
  id_system uuid
  mimic_version varchar
  created_at timestamp
  updated_at timestamp
  migration_name varchar
  resolved boolean /* default false */
  new_system_version varchar /*nullable*/
}
Ref: "mimic_migrations"."id_system" > "mimic_systems"."id"

Table mimic_users {
  id uuid [primary key]
  name varchar
}

Table mimic_user_system {
  id_user uuid [primary key]
  id_system uuid [primary key]
}
Ref: "mimic_user_system"."id_user" > "mimic_users"."id"
Ref: "mimic_user_system"."id_system" > "mimic_systems"."id"

Table mimic_user_role {
  id_user uuid [primary key]
  id_role uuid [primary key]
}
Ref: "mimic_user_role"."id_user" > "mimic_users"."id"
Ref: "mimic_user_role"."id_role" > "mimic_roles"."id"

Table mimic_user_access {
  id_user uuid [primary key]
  id_access uuid [primary key]
}
Ref: "mimic_user_access"."id_user" > "mimic_users"."id"
Ref: "mimic_user_access"."id_access" > "mimic_access"."id"

Table mimic_roles {
  id uuid [primary key]
  name varchar 
  is_default boolean
  roleless_add boolean
}
Ref: "mimic_roles"."id" > "mimic_entities"."id"

Table mimic_access {
  id uuid [primary key]
  id_entity_to_access uuid /*nullable*/
  id_game_state uuid /*nullable*/
  scope enum("self", "same", "other")
  can_read boolean
  can_use boolean
  can_update boolean
  can_create boolean
  can_delete boolean
  can_overwrite boolean
}
Ref: "mimic_access"."id_entity_to_access" > "mimic_entities"."id"
Ref: "mimic_access"."id_game_state" > "mimic_game_states"."id"
Ref: "mimic_access"."id" > "mimic_entities"."id"

Table mimic_role_access {
  id_access uuid [primary key]
  id_role uuid [primary key]
}
Ref: "mimic_role_access"."id_role" > "mimic_roles"."id"
Ref: "mimic_role_access"."id_access" > "mimic_access"."id"

Table mimic_sheet_types {
  id uuid [primary key]
  name varchar 
  id_validation_rule uuid
  id_compose_rule uuid
  category enum("other", "player", "npc", "item", "object")
  id_base_generator uuid // (optional)
  id_default_group uuid // (optional)
}
Ref: "mimic_sheet_types"."id" > "mimic_entities"."id"
Ref: "mimic_sheet_types"."id_validation_rule" > "mimic_rules"."id"
Ref: "mimic_sheet_types"."id_compose_rule" > "mimic_rules"."id"
Ref: "mimic_sheet_types"."id_base_generator" > "mimic_generators"."id"
Ref: "mimic_sheet_types"."id_default_group" > "mimic_sheet_groups"."id"

Table mimic_sheets {
  id uuid [primary key]
  id_sheet_type uuid
}
Ref: "mimic_sheets"."id" > "mimic_entities"."id"
Ref: "mimic_sheets"."id_sheet_type" > "mimic_sheet_types"."id"

Table mimic_sheet_groups {
  id uuid [primary key]
  name varchar
}
Ref: "mimic_sheet_groups"."id" > "mimic_entities"."id"

Table mimic_sheet_group_sheet {
  id_sheet_group uuid [primary key]
  id_sheet uuid [primary key]
}
Ref: "mimic_sheet_group_sheet"."id_sheet_group" > "mimic_sheet_groups"."id"
Ref: "mimic_sheet_group_sheet"."id_sheet" > "mimic_sheets"."id"

Table mimic_generator_types {
  id uuid [primary key]
  name varchar
  id_validation_rule uuid
  id_compose_rule uuid
}
Ref: "mimic_generator_types"."id" > "mimic_entities"."id"
Ref: "mimic_generator_types"."id_validation_rule" > "mimic_rules"."id"
Ref: "mimic_generator_types"."id_compose_rule" > "mimic_rules"."id"

Table mimic_generator_type_steps {
  id uuid [primary key]
  id_generator_type uuid
  id_validation_rule uuid
  name varchar
}
Ref: "mimic_generator_type_steps"."id" > "mimic_entities"."id"
Ref: "mimic_generator_type_steps"."id_generator_type" > "mimic_generator_types"."id"
Ref: "mimic_generator_type_steps"."id_validation_rule" > "mimic_rules"."id"

Table mimic_generators {
  id uuid [primary key]
  id_generator_type uuid
  id_super_generator uuid /* nullable */
  name varchar
}
Ref: "mimic_generators"."id" > "mimic_entities"."id"
Ref: "mimic_generators"."id_generator_type" > "mimic_generator_types"."id"
Ref: "mimic_generators"."id_super_generator" > "mimic_generators"."id"

Table mimic_generator_steps {
  id uuid [primary key]
  id_generator uuid
  id_generator_type_step uuid
  id_validation_rule uuid /* nullable */
  name varchar
}
Ref: "mimic_generator_steps"."id" > "mimic_entities"."id"
Ref: "mimic_generator_steps"."id_generator" > "mimic_generators"."id"
Ref: "mimic_generator_steps"."id_generator_type_step" > "mimic_generator_type_steps"."id"
Ref: "mimic_generator_steps"."id_validation_rule" > "mimic_rules"."id"

Table mimic_generator_step_skill {
  id uuid [primary key]
  id_generator_step uuid
  id_skill uuid
}
Ref: "mimic_generator_step_skill"."id" > "mimic_generator_steps"."id"
Ref: "mimic_generator_step_skill"."id_skill" > "mimic_skills"."id"

Table mimic_sheet_type_generator_type {
  id uuid [primary key]
  id_sheet_type uuid
  id_generator_type uuid
  order integer
}
Ref: "mimic_sheet_type_generator_type"."id_sheet_type" > "mimic_sheet_types"."id"
Ref: "mimic_sheet_type_generator_type"."id_generator_type" > "mimic_generator_types"."id"

Table mimic_skill_types {
  id uuid [primary key]
  name varchar 
  id_validation_rule uuid
}
Ref: "mimic_skill_types"."id" > "mimic_entities"."id"
Ref: "mimic_skill_types"."id_validation_rule" > "mimic_rules"."id"

Table mimic_skills {
  id uuid [primary key]
  id_skill_type uuid
  name varchar
  id_action_rule uuid
}
Ref: "mimic_skills"."id" > "mimic_entities"."id"
Ref: "mimic_skills"."id_skill_type" > "mimic_skill_types"."id"
Ref: "mimic_skills"."id_action_rule" > "mimic_rules"."id"

Table mimic_skill_type_generator_type {
  id_skill_type uuid [primary key]
  id_generator_type uuid [primary key]
}
Ref: "mimic_skill_type_generator_type"."id_skill_type" > "mimic_skill_types"."id"
Ref: "mimic_skill_type_generator_type"."id_generator_type" > "mimic_generator_types"."id"

Table mimic_rules {
  id uuid [primary key]
  name varchar
  type enum("math", "validation", "action", "relationship", "trigger")
  id_trigger_rule uuid /*nullable*/
  rule jsonb /*ast*/
}
Ref: "mimic_rules"."id" > "mimic_entities"."id"
Ref: "mimic_rules"."id_trigger_rule" > "mimic_rules"."id"

Table mimic_rule_entity {

  id uuid [primary key]
  id_rule uuid
  id_entity uuid
  resolve_method enum("manual", "context")
  value_type uuid
  internal_name varchar

}
Ref: "mimic_rule_entity"."id_rule" > "mimic_rules"."id"
Ref: "mimic_rule_entity"."id_entity" > "mimic_entities"."id"
Ref: "mimic_rule_entity"."value_type" > "mimic_value_types"."id"

Table mimic_rngs {
  id uuid [primary key]
  name varchar 
  id_filter_rule uuid /*nullable*/
  expected_value integer /*nullable*/
  num_start integer /*nullable*/
  num_end integer /*nullable*/
  num_step integer /*nullable*/
  final_values integer[]
  type enum("other", "dice", "deck", "spinner")
}
Ref: "mimic_rngs"."id" > "mimic_entities"."id"
Ref: "mimic_rngs"."id_filter_rule" > "mimic_rules"."id"

Table mimic_value_types {
  id uuid [primary key]
  value_type enum("number", "string", "boolean", "entity")
  struct_type enum("value", "list", "consumable", "enum", "key-value")
}

Table mimic_attributes {
  id uuid [primary key]
  id_value_rule uuid
  name varchar 
  value_type uuid
  expected_value_number number /*nullable*/
  expected_value_string varchar /*nullable*/
  expected_value_boolean boolean /*nullable*/
  expected_value_entity uuid /*nullable*/
  default_value_number number /*nullable*/
  default_value_string varchar /*nullable*/
  default_value_boolean boolean /*nullable*/
  default_value_entity uuid /*nullable*/
  is_composable boolean /*default true*/
  is_constant boolean /*default false*/
  min_size_value integer /*nullable*/
  max_size_value integer /*nullable*/
}
Ref: "mimic_attributes"."id" > "mimic_entities"."id"
Ref: "mimic_attributes"."id_value_rule" > "mimic_rules"."id"
Ref: "mimic_attributes"."value_type" > "mimic_value_types"."id"
Ref: "mimic_attributes"."expected_value_entity" > "mimic_entities"."id"
Ref: "mimic_attributes"."default_value_entity" > "mimic_entities"."id"

Table mimic_entity_attribute {
  id uuid [primary key]
  id_entity uuid
  id_attribute uuid
}
Ref: "mimic_entity_attribute"."id_entity" > "mimic_entities"."id"
Ref: "mimic_entity_attribute"."id_attribute" > "mimic_attributes"."id"

Table mimic_entity_attribute_entry {
  id uuid [primary key]
  id_entity_attribute uuid
  attribute_number number /*nullable*/
  attribute_string varchar /*nullable*/
  attribute_boolean boolean /*nullable*/
  attribute_entity uuid /*nullable*/
  order integer /*default 1*/
}
Ref: "mimic_entity_attribute_entry"."id_entity_attribute" > "mimic_entity_attribute"."id"
Ref: "mimic_entity_attribute_entry"."attribute_entity" > "mimic_entities"."id"

Table mimic_attribute_items {
  id uuid [primary key]
  id_attribute_composer uuid
  id_attribute_composable uuid
  name varchar
}
Ref: "mimic_attribute_items"."id_attribute_composer" > "mimic_attributes"."id"
Ref: "mimic_attribute_items"."id_attribute_composable" > "mimic_attributes"."id"

Table mimic_globals {
  id uuid [primary key]
  id_attribute uuid
  name varchar
}
Ref: "mimic_globals"."id" > "mimic_entities"."id"
Ref: "mimic_globals"."id_attribute" > "mimic_attributes"."id"

Table mimic_test_types {
  id uuid [primary key]
  id_default_rule uuid /*nullable*/
  name varchar
}
Ref: "mimic_test_types"."id" > "mimic_entities"."id"
Ref: "mimic_test_types"."id_default_rule" > "mimic_rules"."id"

Table mimic_tests {
  id uuid [primary key]
  id_test_type uuid
  id_rule uuid /*nullable*/
  name varchar
}
Ref: "mimic_tests"."id" > "mimic_entities"."id"
Ref: "mimic_tests"."id_test_type" > "mimic_test_types"."id"
Ref: "mimic_tests"."id_rule" > "mimic_rules"."id"

Table mimic_test_rng {
  id_test uuid [primary key]
  id_rng uuid [primary key]
}
Ref: "mimic_test_rng"."id_test" > "mimic_tests"."id"
Ref: "mimic_test_rng"."id_rng" > "mimic_rngs"."id"

Table mimic_game_states {
  id uuid [primary key]
  name varchar 
  turn_count_rule_id uuid
  turn_order_rule_id uuid
}
Ref: "mimic_game_states"."id" > "mimic_entities"."id"
Ref: "mimic_game_states"."turn_count_rule_id" > "mimic_rules"."id"
Ref: "mimic_game_states"."turn_order_rule_id" > "mimic_rules"."id"

Table mimic_systems {
  id uuid [primary key]
  mimic_version varchar
  name varchar
  system_version varchar
  id_author_user uuid
  system_hash varchar /*nullable*/
  created_at timestamp
  updated_at timestamp
  type enum("root", "delta")
  id_delta_origin uuid /*nullable*/
  actual_game_state uuid
  actual_turn uuid
}
Ref: "mimic_systems"."id_delta_origin" > "mimic_systems"."id"
Ref: "mimic_systems"."id_author_user" > "mimic_users"."id"
Ref: "mimic_systems"."actual_game_state" > "mimic_game_states"."id"
Ref: "mimic_systems"."actual_turn" > "mimic_entities"."id"

Table mimic_event_logs {

  id uuid [primary key]
  created_at timestamp
  id_entity uuid
  event_type enum("free", "narrative" ,"mimic")
  mimic_event enum("read", "use", "update", "create", "delete", "overwrite") /*nullable*/
  narrative_event enum("other", "dialog", "action", "narration") /*nullable*/
  entry text
  multi_part_id uuid /*nullable*/
  resolved boolean

}
Ref: "mimic_event_logs"."id_entity" > "mimic_entities"."id"

Table mimic_tags {
  id uuid [primary key]
  id_system uuid
  name varchar 
}
Ref: "mimic_tags"."id_system" > "mimic_systems"."id"

Table mimic_tag_entity {
  id_tag uuid [primary key]
  id_entity uuid [primary key]
}
Ref: "mimic_tag_entity"."id_tag" > "mimic_tags"."id"
Ref: "mimic_tag_entity"."id_entity" > "mimic_entities"."id"

Table mimic_entities {
  id uuid [primary key]
  created_at timestamp
  updated_at timestamp
  id_system uuid
  id_creator_user uuid
  emphasis_level enum("hidden", "common", "featured")
  id_overrides_entity uuid /*nullable*/
  table_name varchar /*ex: generators, rules, roles etc*/
  is_active boolean /*default true*/
}
Ref: "mimic_entities"."id_overrides_entity" > "mimic_entities"."id"
Ref: "mimic_entities"."id_creator_user" > "mimic_users"."id"
Ref: "mimic_entities"."id_system" > "mimic_systems"."id"

Table mimic_maps {
  id uuid [primary key]
  name varchar 
  size_a integer
  size_b integer
  size_c integer
  map_system enum("xyz", "qrs")
  multi_map boolean 
}
Ref: "mimic_maps"."id" > "mimic_entities"."id"

Table mimic_map_map {
  id_map_origin uuid [primary key]
  id_map_destination uuid [primary key]
  distance integer
  expand_a integer /*Nullable*/
  expand_b integer /*Nullable*/
  expand_c integer /*Nullable*/
}
Ref: "mimic_map_map"."id_map_origin" > "mimic_maps"."id"
Ref: "mimic_map_map"."id_map_destination" > "mimic_maps"."id"

Table mimic_map_token {
  id uuid [primary key]
  id_sheet uuid /*nullable*/
  id_map uuid
  position_a integer
  position_b integer
  position_c integer
  size_a integer
  size_b integer
  size_c integer
  origin_a integer
  origin_b integer
  origin_c integer
  angle_a integer /*0-360*/
  angle_b integer /*0-360*/
  angle_c integer /*0-360*/
  solid_level integer
}
Ref: "mimic_map_token"."id" > "mimic_entities"."id"
Ref: "mimic_map_token"."id_sheet" > "mimic_sheets"."id"
Ref: "mimic_map_token"."id_map" > "mimic_maps"."id"

Table mimic_description_variant_types {
  id uuid [primary key]
  id_system uuid
  name varchar
}
Ref: "mimic_description_variant_types"."id_system" > "mimic_systems"."id"

Table mimic_description_variants {
  id uuid [primary key]
  id_description_variant_type uuid
  name varchar
}
Ref: "mimic_description_variants"."id_description_variant_type" > "mimic_description_variant_types"."id"

Table mimic_description_description_variant {
  id_description uuid [primary key]
  id_description_variant uuid [primary key]
}
Ref: "mimic_description_description_variant"."id_description" > "mimic_descriptions"."id"
Ref: "mimic_description_description_variant"."id_description_variant" > "mimic_description_variants"."id"

Table mimic_descriptions {
  id uuid [primary key]
  id_entity uuid
  description text
  image_type enum("other", "illustration", "icon", "diagram", "full_page", "banner", "main_folder")
  image_link varchar /* nullable */
}
Ref: "mimic_descriptions"."id_entity" > "mimic_entities"."id"

Table mimic_sheet_generator {
  id_sheet_generator uuid [primary key]
  id_sheet uuid
  id_generator uuid
  order integer
}
Ref: "mimic_sheet_generator"."id_sheet" > "mimic_sheets"."id"
Ref: "mimic_sheet_generator"."id_generator" > "mimic_generators"."id"

Table mimic_sheet_skill {
  id uuid [primary key]
  id_sheet uuid
  id_skill uuid
}
Ref: "mimic_sheet_skill"."id_sheet" > "mimic_sheets"."id"
Ref: "mimic_sheet_skill"."id_skill" > "mimic_skills"."id"

Table mimic_sheet_skill_attribute_entry {
  id uuid [primary key]
  id_sheet_skill uuid
  id_attribute uuid
  attribute_number number /*nullable*/
  attribute_string varchar /*nullable*/
  attribute_boolean boolean /*nullable*/
  attribute_entity uuid /*nullable*/
  order integer
}
Ref: "mimic_sheet_skill_attribute_entry"."id_sheet_skill" > "mimic_sheet_skill"."id"
Ref: "mimic_sheet_skill_attribute_entry"."id_attribute" > "mimic_attributes"."id"
Ref: "mimic_sheet_skill_attribute_entry"."attribute_entity" > "mimic_entities"."id"

Table mimic_sheet_type_sheet_type {
  id_sheet_type_main uuid [primary key]
  id_sheet_type_children uuid [primary key]
  id_relationship_rule uuid
}
Ref: "mimic_sheet_type_sheet_type"."id_sheet_type_main" > "mimic_sheet_types"."id"
Ref: "mimic_sheet_type_sheet_type"."id_sheet_type_children" > "mimic_sheet_types"."id"
Ref: "mimic_sheet_type_sheet_type"."id_relationship_rule" > "mimic_rules"."id"

Table mimic_sheet_sheet {
  id uuid [primary key]
  id_sheet_main uuid
  id_sheet_children uuid
  order integer
}
Ref: "mimic_sheet_sheet"."id_sheet_main" > "mimic_sheets"."id"
Ref: "mimic_sheet_sheet"."id_sheet_children" > "mimic_sheets"."id"
