Table roles {
  id_role integer [primary key]
  id_entity integer
  name varchar unique
  is_default bool
  roleless_add bool
}

Table access {
  id_access integer [primary key]
  id_entity integer
  id_entity_to_access integer /*nullable*/
  id_game_state integer /*nullable*/
  scope enum("self", "same", "other")
  action bitmask("read", "use", "update", "create", "delete", "overwrite")
}

Table role_access {
  id_role_access integer [primary key]
  id_access integer
  id_role integer
}

Table sheet_types {
  id_sheet_type integer [primary key]
  id_entity integer
  name varchar unique
  id_validation_rule integer
}

Table sheets {
  id_sheet integer [primary key]
  id_entity integer
  id_sheet_type integer
  data json
  x_size integer
  y_size integer
  z_size integer
  origin integer
}

Table generator_types {
  id_generator_type integer [primary key]
  id_entity integer
  name varchar unique
  schema json
  id_validation_rule integer
}

Table generator_type_steps {

  id_generator_type_step integer [primary key]
  id_entity integer
  id_generator_type integer
  id_trigger_rule integer
  id_validation_rule integer
  name varchar

}

Table generators {
  id_generator integer [primary key]
  id_entity integer
  id_generator_type integer
  id_super_generator integer
  is_children boolean /*default false*/
  name varchar unique
  data json
}

Table generator_steps {
  id_generator_step integer [primary key]
  id_entity integer
  id_generator integer
  id_generator_type_step integer
  name varchar
  data json
}

Table sheet_type_generator_type {
  id_sheet_type_generator_type integer [primary key]
  id_sheet_type integer
  id_generator_type integer
}

Table skill_types {
  id_skill_type integer [primary key]
  id_entity integer
  name varchar unique
  id_validation_rule integer
}

Table skills {
  id_skill integer [primary key]
  id_entity integer
  id_skill_type integer
  name varchar
  id_action_rule integer
}

Table skill_type_generator_type {
  id_skill_type_generator_type integer [primary key]
  id_skill_type integer
  id_generator_type integer
}

Table rules {
  id_rule integer [primary key]
  id_entity integer
  name varchar
  type varchar
  rule json /*ast*/
}

Table rngs {
  id_rng integer [primary key]
  id_entity integer
  name varchar unique
  expected_value integer /*nullable*/
  filter_rule_id integer /*nullable*/
  generator_start integer /*nullable default 1*/
  generator_end integer
  generator_step integer /*nullable default 1*/
  cached_values integer[]
}

Table atributes {
  id_atribute integer [primary key]
  id_entity integer
  name varchar unique
  id_value_rule integer
  value_type enum("int", "string", "bool", "enum")
  default_value varchar /*nullable*/
  is_composable boolean /*default true*/
}

Table atribute_items {
  id_atribute_item integer [primary key]
  id_atribute_composer integer
  id_atribute_composable integer
  name varchar
}

Table globals {
  id_global integer [primary key]
  id_entity integer
  id_atribute integer
  name varchar unique
  is_constant bool
}

Table tests {
  id_test integer [primary key]
  id_entity integer
  name varchar unique
  id_rule integer
}

Table test_atribute {
  id_test_atribute integer [primary key]
  id_test integer
  id_atribute integer
}

Table test_rng {
  id_test_rng integer [primary key]
  id_test integer
  id_rng integer
}

Table atribute_generator_type {
  id_atribute_generator_type integer [primary key]
  id_atribute integer
  id_generator_type integer
}

Table game_states {
  id_game_state integer [primary key]
  id_entity integer
  name varchar unique
  turn_count_rule_id integer
  turn_order_rule_id integer
}

Table systems {
  id_system integer [primary key]
  mimic_version_l1 integer
  mimic_version_l2 integer
  mimic_version_l3 integer
  name varchar
  system_version_l1 varchar
  system_version_l2 varchar
  system_version_l3 varchar
  author varchar
  system_hash varchar
  created_at timestamp
  updated_at timestamp
  type enum("root", "delta")
}

Table tags {
  id_tag integer [primary key]
  name varchar unique
}

Table tag_entity {

  id_tag_entity integer [primary key]
  id_tag integer
  id_entity integer

}

Table entities {
  id_entity integer [primary key]
  created_at timestamp
  updated_at timestamp
  id_system integer
  table_name varchar
}

Table maps {
  id_map integer [primary key]
  id_entity integer
  name varchar unique
  x_size integer
  y_size integer
  z_size integer
}

Table map_sheet {

  id_map_sheet integer
  id_sheet integer
  id_map integer
  x integer
  y integer
  z integer

}

Table description_variant_types {

  id_description_variant_type integer [primary key]
  name varchar

}

Table description_variants {

  id_description_variant integer [primary key]
  id_description_variant_type integer
  name varchar

}

Table descriptions {
  id_description integer [primary key]
  id_entity integer
  name varchar
  description text
  id_description_variant integer
}

Ref: "rngs"."id_rng" < "test_rng"."id_rng"

Ref: "tests"."id_test" < "test_rng"."id_test"

Ref: "tests"."id_test" < "test_atribute"."id_test"

Ref: "atributes"."id_atribute" < "test_atribute"."id_atribute"

Ref: "atributes"."id_atribute" < "globals"."id_atribute"

Ref: "atributes"."id_atribute" < "atribute_generator_type"."id_atribute"

Ref: "skills"."id_skill" < "skill_type_generator_type"."id_skill_type"

Ref: "roles"."id_role" < "role_access"."id_role"

Ref: "access"."id_access" < "role_access"."id_access"

Ref: "skills"."id_skill_type" <
"skill_types"."id_skill_type"

Ref: "generators"."id_generator_type" <
"generator_types"."id_generator_type"

Ref: "sheet_type_generator_type"."id_generator_type" > "generator_types"."id_generator_type"

Ref: "atribute_generator_type"."id_generator_type" >
"generator_types"."id_generator_type"

Ref: "skill_type_generator_type"."id_generator_type" >
"generator_types"."id_generator_type"

Ref: "sheet_type_generator_type"."id_sheet_type" >
"sheet_types"."id_sheet_type"

Ref: "access"."id_entity_to_access" >
"entities"."id_entity"

Ref: "access"."id_game_state" >
"game_states"."id_game_state"

Ref: "tests"."id_rule" >
"rules"."id_rule"

Ref: "rngs"."filter_rule_id" >
"rules"."id_rule"

Ref: "atributes"."id_value_rule" >
"rules"."id_rule"

Ref: "sheet_types"."id_validation_rule" >
"rules"."id_rule"

Ref: "skill_types"."id_validation_rule" >
"rules"."id_rule"

Ref: "skills"."id_action_rule" >
"rules"."id_rule"

Ref: "atribute_items"."id_atribute_composer" >
"atributes"."id_atribute"

Ref: "atribute_items"."id_atribute_composable" >
"atributes"."id_atribute"

Ref: "game_states"."turn_count_rule_id" >
"rules"."id_rule"

Ref: "game_states"."turn_order_rule_id" >
"rules"."id_rule"

Ref: "map_sheet"."id_map" >
"maps"."id_map"

Ref: "map_sheet"."id_sheet" >
"sheets"."id_sheet"

Ref: "sheets"."id_sheet_type" >
"sheet_types"."id_sheet_type"

Ref: "generator_types"."id_validation_rule" >
"rules"."id_rule"

Ref: "generator_type_steps"."id_generator_type" >
"generator_types"."id_generator_type"

Ref: "generator_type_steps"."id_trigger_rule" >
"rules"."id_rule"

Ref: "generator_type_steps"."id_validation_rule" >
"rules"."id_rule"

Ref: "generator_steps"."id_generator" >
"generators"."id_generator"

Ref: "generator_steps"."id_generator_type_step" >
"generator_type_steps"."id_generator_type_step"

Ref: "generators"."id_super_generator" >
"generators"."id_generator"

Ref: "entities"."id_system" >
"systems"."id_system"

Ref: "roles"."id_entity" >
"entities"."id_entity"

Ref: "generators"."id_entity" >
"entities"."id_entity"

Ref: "rules"."id_entity" >
"entities"."id_entity"

Ref: "maps"."id_entity" >
"entities"."id_entity"

Ref: "sheet_types"."id_entity" >
"entities"."id_entity"

Ref: "generator_types"."id_entity" >
"entities"."id_entity"

Ref: "skills"."id_entity" >
"entities"."id_entity"

Ref: "atributes"."id_entity" >
"entities"."id_entity"

Ref: "rngs"."id_entity" >
"entities"."id_entity"

Ref: "tests"."id_entity" >
"entities"."id_entity"

Ref: "game_states"."id_entity" >
"entities"."id_entity"

Ref: "sheets"."id_entity" >
"entities"."id_entity"

Ref: "generator_type_steps"."id_entity" >
"entities"."id_entity"

Ref: "skill_types"."id_entity" >
"entities"."id_entity"

Ref: "globals"."id_entity" >
"entities"."id_entity"

Ref: "access"."id_entity" >
"entities"."id_entity"

Ref: "generator_steps"."id_entity" >
"entities"."id_entity"

Ref: "description_variants"."id_description_variant_type" >
"description_variant_types"."id_description_variant_type"

Ref: "descriptions"."id_description_variant" >
"description_variants"."id_description_variant"

Ref: "descriptions"."id_entity" >
"entities"."id_entity"

Ref: "tag_entity"."id_tag" >
"tags"."id_tag"

Ref:"tag_entity"."id_entity" >
"entities"."id_entity"