Table users {
  id_user integer
  name varchar
}

Table user_system {
  id_user integer [primary key]
  id_system integer [primary key]
}
Ref: "user_system"."id_user" > "users"."id_user"
Ref: "user_system"."id_system" > "systems"."id_system"

Table user_role {
  id_user integer [primary key]
  id_role integer [primary key]
}
Ref: "user_role"."id_user" > "users"."id_user"
Ref: "user_role"."id_role" > "roles"."id_role"

Table roles {
  id_role integer [primary key]
  name varchar 
  is_default bool
  roleless_add bool
}
Ref: "roles"."id_role" > "entities"."id_entity"

Table access {
  id_access integer [primary key]
  id_entity_to_access integer /*nullable*/
  id_game_state integer /*nullable*/
  scope enum("self", "same", "other")
  can_read boolean
  can_use boolean
  can_update boolean
  can_create boolean
  can_delete boolean
  can_overwrite boolean
}
Ref: "access"."id_entity_to_access" > "entities"."id_entity"
Ref: "access"."id_game_state" > "game_states"."id_game_state"
Ref: "access"."id_access" > "entities"."id_entity"

Table role_access {
  id_access integer [primary key]
  id_role integer [primary key]
}
Ref: "role_access"."id_role" > "roles"."id_role"
Ref: "role_access"."id_access" > "access"."id_access"

Table sheet_types {
  id_sheet_type integer [primary key]
  name varchar 
  id_validation_rule integer
  id_compose_rule integer
}
Ref: "sheet_types"."id_sheet_type" > "entities"."id_entity"
Ref: "sheet_types"."id_validation_rule" > "rules"."id_rule"
Ref: "sheet_types"."id_compose_rule" > "rules"."id_rule"

Table sheets {
  id_sheet integer [primary key]
  id_sheet_type integer
}
Ref: "sheets"."id_sheet" > "entities"."id_entity"
Ref: "sheets"."id_sheet_type" > "sheet_types"."id_sheet_type"

Table generator_types {
  id_generator_type integer [primary key]
  name varchar
  id_validation_rule integer
  id_compose_rule integer
}
Ref: "generator_types"."id_generator_type" > "entities"."id_entity"
Ref: "generator_types"."id_validation_rule" > "rules"."id_rule"
Ref: "generator_types"."id_compose_rule" > "rules"."id_rule"

Table generator_type_steps {
  id_generator_type_step integer [primary key]
  id_generator_type integer
  id_trigger_rule integer
  id_validation_rule integer
  name varchar
}
Ref: "generator_type_steps"."id_generator_type_step" > "entities"."id_entity"
Ref: "generator_type_steps"."id_generator_type" > "generator_types"."id_generator_type"
Ref: "generator_type_steps"."id_trigger_rule" > "rules"."id_rule"
Ref: "generator_type_steps"."id_validation_rule" > "rules"."id_rule"

Table generators {
  id_generator integer [primary key]
  id_generator_type integer
  id_super_generator integer /* nullable */
  is_children boolean /*default false*/
  name varchar
}
Ref: "generators"."id_generator" > "entities"."id_entity"
Ref: "generators"."id_generator_type" > "generator_types"."id_generator_type"
Ref: "generators"."id_super_generator" > "generators"."id_generator"

Table generator_steps {
  id_generator_step integer [primary key]
  id_generator integer
  id_generator_type_step integer
  name varchar
}
Ref: "generator_steps"."id_generator_step" > "entities"."id_entity"
Ref: "generator_steps"."id_generator" > "generators"."id_generator"
Ref: "generator_steps"."id_generator_type_step" > "generator_type_steps"."id_generator_type_step"

Table generator_step_attribute {
  id_generator_step integer [primary key]
  id_attribute integer [primary key]
  attribute_entry text
}
Ref: "generator_step_attribute"."id_generator_step" > "generator_steps"."id_generator_step"
Ref: "generator_step_attribute"."id_attribute" > "attributes"."id_attribute"

Table generator_step_skill {
  id_generator_step_skill integer [primary key]
  id_generator_step integer
  id_skill integer
}
Ref: "generator_step_skill"."id_generator_step" > "generator_steps"."id_generator_step"
Ref: "generator_step_skill"."id_skill" > "skills"."id_skill"

Table generator_step_skill_attribute {
  id_generator_step_skill integer [primary key]
  id_attribute integer [primary key]
  attribute_entry text
}
Ref: "generator_step_skill_attribute"."id_generator_step_skill" > "generator_step_skill"."id_generator_step_skill"
Ref: "generator_step_skill_attribute"."id_attribute" > "attributes"."id_attribute"

Table sheet_type_generator_type {
  id_sheet_type_generator_type integer [primary key]
  id_sheet_type integer
  id_generator_type integer
  order integer
}
Ref: "sheet_type_generator_type"."id_sheet_type" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_generator_type"."id_generator_type" > "generator_types"."id_generator_type"

Table skill_types {
  id_skill_type integer [primary key]
  name varchar 
  id_validation_rule integer
}
Ref: "skill_types"."id_skill_type" > "entities"."id_entity"
Ref: "skill_types"."id_validation_rule" > "rules"."id_rule"

Table skills {
  id_skill integer [primary key]
  id_skill_type integer
  name varchar
  id_action_rule integer
}
Ref: "skills"."id_skill" > "entities"."id_entity"
Ref: "skills"."id_skill_type" > "skill_types"."id_skill_type"
Ref: "skills"."id_action_rule" > "rules"."id_rule"

Table skill_type_generator_type {
  id_skill_type integer [primary key]
  id_generator_type integer [primary key]
}
Ref: "skill_type_generator_type"."id_skill_type" > "skill_types"."id_skill_type"
Ref: "skill_type_generator_type"."id_generator_type" > "generator_types"."id_generator_type"

Table rules {
  id_rule integer [primary key]
  name varchar
  type varchar
  rule jsonb /*ast*/
}
Ref: "rules"."id_rule" > "entities"."id_entity"

Table rngs {
  id_rng integer [primary key]
  name varchar 
  id_filter_rule integer /*nullable*/
  expected_value integer /*nullable*/
  generator_start integer /*nullable default 1*/
  generator_end integer
  generator_step integer /*nullable default 1*/
  cached_values integer[]
}
Ref: "rngs"."id_rng" > "entities"."id_entity"
Ref: "rngs"."id_filter_rule" > "rules"."id_rule"

Table attributes {
  id_attribute integer [primary key]
  id_value_rule integer
  name varchar 
  value_type enum("int", "float", "string", "bool", "enum")
  default_value varchar /*nullable*/
  is_composable boolean /*default true*/
}
Ref: "attributes"."id_attribute" > "entities"."id_entity"
Ref: "attributes"."id_value_rule" > "rules"."id_rule"

Table attribute_items {
  id_attribute_item integer [primary key]
  id_attribute_composer integer
  id_attribute_composable integer
  name varchar
}
Ref: "attribute_items"."id_attribute_composer" > "attributes"."id_attribute"
Ref: "attribute_items"."id_attribute_composable" > "attributes"."id_attribute"

Table globals {
  id_global integer [primary key]
  id_attribute integer
  name varchar 
  is_constant bool
}
Ref: "globals"."id_global" > "entities"."id_entity"
Ref: "globals"."id_attribute" > "attributes"."id_attribute"

Table tests {
  id_test integer [primary key]
  name varchar 
  id_rule integer
}
Ref: "tests"."id_test" > "entities"."id_entity"
Ref: "tests"."id_rule" > "rules"."id_rule"

Table test_attribute {
  id_test integer [primary key]
  id_attribute integer [primary key]
}
Ref: "test_attribute"."id_test" > "tests"."id_test"
Ref: "test_attribute"."id_attribute" > "attributes"."id_attribute"

Table test_rng {
  id_test integer [primary key]
  id_rng integer [primary key]
}
Ref: "test_rng"."id_test" > "tests"."id_test"
Ref: "test_rng"."id_rng" > "rngs"."id_rng"

Table attribute_generator_type {
  id_attribute integer [primary key]
  id_generator_type integer [primary key]
}
Ref: "attribute_generator_type"."id_attribute" > "attributes"."id_attribute"
Ref: "attribute_generator_type"."id_generator_type" > "generator_types"."id_generator_type"

Table game_states {
  id_game_state integer [primary key]
  name varchar 
  turn_count_rule_id integer
  turn_order_rule_id integer
}
Ref: "game_states"."id_game_state" > "entities"."id_entity"
Ref: "game_states"."turn_count_rule_id" > "rules"."id_rule"
Ref: "game_states"."turn_order_rule_id" > "rules"."id_rule"

Table systems {
  id_system integer [primary key]
  mimic_version varchar
  name varchar
  system_version varchar
  id_author_user integer
  system_hash varchar
  created_at timestamp
  updated_at timestamp
  type enum("root", "delta")
  id_delta_origin integer /*nullable*/
}
Ref: "systems"."id_delta_origin" > "systems"."id_system"
Ref: "systems"."id_author_user" > "users"."id_user"

Table tags {
  id_tag integer [primary key]
  id_system integer
  name varchar 
}
Ref: "tags"."id_system" > "systems"."id_system"

Table tag_entity {
  id_tag integer [primary key]
  id_entity integer [primary key]
}
Ref: "tag_entity"."id_tag" > "tags"."id_tag"
Ref: "tag_entity"."id_entity" > "entities"."id_entity"

Table entities {
  id_entity integer [primary key]
  created_at timestamp
  updated_at timestamp
  id_system integer
  id_creator_user integer
  id_overrides_entity integer /*nullable*/
  table_name varchar /*ex: generators, rules, roles etc*/
}
Ref: "entities"."id_overrides_entity" > "entities"."id_entity"
Ref: "entities"."id_creator_user" > "users"."id_user"
Ref: "entities"."id_system" > "systems"."id_system"

Table maps {
  id_map integer [primary key]
  name varchar 
  x_size integer
  y_size integer
  z_size integer
}
Ref: "maps"."id_map" > "entities"."id_entity"

Table map_token {
  id_map_token integer [primary key]
  id_sheet integer
  id_map integer
  x integer
  y integer
  z integer
  x_size integer
  y_size integer
  z_size integer
  origin integer
  angle_x integer /*0-360*/
  angle_y integer /*0-360*/
  angle_z integer /*0-360*/
}
Ref: "map_token"."id_sheet" > "sheets"."id_sheet"
Ref: "map_token"."id_map" > "maps"."id_map"

Table description_variant_types {
  id_description_variant_type integer [primary key]
  id_system integer
  name varchar
}
Ref: "description_variant_types"."id_system" > "systems"."id_system"

Table description_variants {
  id_description_variant integer [primary key]
  id_description_variant_type integer
  name varchar
}
Ref: "description_variants"."id_description_variant_type" > 
"description_variant_types"."id_description_variant_type"

Table descriptions {
  id_description integer [primary key]
  id_entity integer
  name varchar
  description text
  id_description_variant integer
}
Ref: "descriptions"."id_entity" > "entities"."id_entity"
Ref: "descriptions"."id_description_variant" > 
"description_variants"."id_description_variant"

Table sheet_type_attribute {
  id_sheet_type integer [primary key]
  id_attribute integer [primary key]
}
Ref: "sheet_type_attribute"."id_sheet_type" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_attribute"."id_attribute" > "attributes"."id_attribute"

Table sheet_generator {
  id_sheet_generator integer [primary key]
  id_sheet integer
  id_generator integer
  order integer
}
Ref: "sheet_generator"."id_sheet" > "sheets"."id_sheet"
Ref: "sheet_generator"."id_generator" > "generators"."id_generator"

Table sheet_attribute {
  id_sheet integer [primary key]
  id_attribute integer [primary key]
  attribute_entry text
}
Ref: "sheet_attribute"."id_sheet" > "sheets"."id_sheet"
Ref: "sheet_attribute"."id_attribute" > "attributes"."id_attribute"

Table sheet_skill {
  id_sheet integer [primary key]
  id_skill integer [primary key]
}
Ref: "sheet_skill"."id_sheet" > "sheets"."id_sheet"
Ref: "sheet_skill"."id_skill" > "skills"."id_skill"

Table sheet_skill_attribute {
  id_sheet_skill integer [primary key]
  id_attribute integer [primary key]
  attribute_entry text
}
Ref: "sheet_skill_attribute"."id_sheet_skill" > "sheet_skill"."id_sheet_skill"
Ref: "sheet_skill_attribute"."id_attribute" > "attributes"."id_attribute"

Table sheet_type_sheet_type {
  id_sheet_type_main integer [primary key]
  id_sheet_type_children integer [primary key]
  id_relationship_rule integer
}
Ref: "sheet_type_sheet_type"."id_sheet_type_main" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_sheet_type"."id_sheet_type_children" > "sheet_types"."id_sheet_type"
Ref: "sheet_type_sheet_type"."id_relationship_rule" > "rules"."id_rule"

Table sheet_sheet {
  id_sheet_sheet integer [primary key]
  id_sheet_main integer
  id_sheet_children integer
}
Ref: "sheet_sheet"."id_sheet_main" > "sheets"."id_sheet"
Ref: "sheet_sheet"."id_sheet_children" > "sheets"."id_sheet"
